stages:
  - analysis
  - test
  - build
  - deploy

workflow:
  rules:
    - when: always

variables:
  GIT_DEPTH: 1

.tags_win10_conda:
  tags: ["eo", "win10", "conda"]

.tags_manylinux_2_28_std:
  tags: ["manylinux_2_28"]

.tags_manylinux_2_28:
  tags: ["eotools_manylinux228"]

.tags_win10_new:
  tags: ["eotools_win10"]

.tags_deploy:
  tags: ["eo", "deploy"]

default:
  before_script:
    - cd $SUBPROJECT

# === analysis ===============================================================
# ============================================================================
check_code_compliance_ruff:
  stage: analysis
  extends:
    - .tags_manylinux_2_28_std
  script:
    - python3.12 -m pip install nox
    - python3.12 -m nox -s check_format

check_code_compliance_pylint:
  stage: analysis
  extends:
    - .tags_manylinux_2_28_std
  script:
    - python3.12 -m pip install nox
    - python3.12 -m nox -s pylint

# === test - unittest ========================================================
# ============================================================================
unittest_linux:
  stage: test
  script:
    - python${PYTHON} -m pip install nox
    - python${PYTHON} -m nox -s unittest -p ${PYTHON}
  parallel:
    matrix:
      - PYTHON: ["3.10", "3.11", "3.12", "3.13"]
  extends: .tags_manylinux_2_28_std
  needs: []
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit:
        - ${SUBPROJECT}/_build/unittest-report-*.xml
      coverage_report:
        coverage_format: cobertura
        path: ${SUBPROJECT}/_build/unittest-coverage-*.xml

unittest_win:
  stage: test
  script:
    - . "C:\Users\ContainerAdministrator\Documents\WindowsPowerShell\profile.ps1"
    - conda create -y -n integration_test python=${PYTHON}
    - conda activate integration_test
    - python -m pip install nox
    - python -m nox -s unittest -p ${PYTHON}
  parallel:
    matrix:
      - PYTHON: ["3.10", "3.11", "3.12", "3.13"]
  needs: []
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  extends: .tags_win10_new
  artifacts:
    reports:
      junit:
        - ${SUBPROJECT}/_build/unittest-report-*.xml
      coverage_report:
        coverage_format: cobertura
        path: ${SUBPROJECT}/_build/unittest-coverage-*.xml

# === test - integration =====================================================
# ============================================================================
integration_test_linux:
  stage: test
  script:
    - python${PYTHON} -m venv ./ci_test
    - source ./ci_test/bin/activate
    - python -m pip install .[test]
    - sct-testing -r ./tests/test_registry_linux.json -out ./test_output
  parallel:
    matrix:
      - PYTHON: ["3.10", "3.11", "3.12", "3.13"]
  extends: .tags_manylinux_2_28
  needs: []

integration_test_windows:
  stage: test
  script:
    - . "C:\Users\ContainerAdministrator\Documents\WindowsPowerShell\profile.ps1"
    - conda create -y -n integration_test python=${PYTHON}
    - conda activate integration_test
    - python -m pip install -e .[test]
    - sct-testing -r ./tests/test_registry_windows.json -out ./test_output
  parallel:
    matrix:
      - PYTHON: ["3.10", "3.11", "3.12", "3.13"]
  extends: .tags_win10_new
  needs: []

# === build ==================================================================
# ============================================================================
sdist:
  stage: build
  extends:
    - .tags_manylinux_2_28_std
  script:
    - python3.12 -m pip install nox
    - python3.12 -m nox -s build_sdist
  needs: []
  artifacts:
    expire_in: 2 weeks
    paths:
      - ${SUBPROJECT}/dist/*.tar.gz

wheel:
  stage: build
  extends:
    - .tags_manylinux_2_28_std
  script:
    - python3.12 -m pip install nox
    - python3.12 -m nox -s build_wheel
  needs: []
  artifacts:
    expire_in: 2 weeks
    paths:
      - ${SUBPROJECT}/dist/*.whl

doc:
  stage: build
  extends:
    - .tags_manylinux_2_28_std
  script:
    - yum install -y pandoc
    - python3.12 -m pip install nox
    - python3.12 -m nox -s build_doc
  needs: []
  artifacts:
    expire_in: 2 weeks
    paths:
      - ${SUBPROJECT}/docs/build/*.zip

# === deploy =================================================================
# ============================================================================
deploy_package:
  stage: deploy
  extends: .tags_deploy
  rules:
    - if: "$CI_COMMIT_TAG"
  script:
    - eval "$(ssh-agent -s)"
    - cd ..
    - for file in ${SUBPROJECT}/dist/*.tar.gz ${SUBPROJECT}/dist/*.whl; do
      eo_pgp-signme ${file} > ${file}.asc &&
      ./.gitlab/ci/dashboard-copy.sh ${file} develop/sct-plugins/saocom/archive &&
      ./.gitlab/ci/dashboard-copy.sh ${file}.asc develop/sct-plugins/saocom/archive;
      done

deploy_doc:
  stage: deploy
  extends: .tags_deploy
  rules:
    - if: "$CI_COMMIT_TAG"
    - if: '$DEPLOY_DOC == "true"'
  before_script:
    - export PACKAGE_VERSION=v$(grep "__version__" $SUBPROJECT/src/sct_saocom_reader/__init__.py | awk -F '"' '{print $2}')
  script:
    - eval "$(ssh-agent)"
    - cat "$DASHBOARD_PRIVATE_KEY" | base64 -d | ssh-add -
    - for file in ${SUBPROJECT}/docs/build/*.zip; do
      eo_pgp-signme ${file} > ${file}.asc &&
      ./.gitlab/ci/dashboard-copy.sh ${file} develop/sct-plugins/saocom/archive &&
      ./.gitlab/ci/dashboard-copy.sh ${file}.asc develop/sct-plugins/saocom/archive;
      done
    - unzip ${SUBPROJECT}/docs/build/*.zip
    - mv *${SUBPROJECT}*-html-doc ${PACKAGE_VERSION}
    - rsync --stats -r ${PACKAGE_VERSION} sardashboard@intranet.aresys.it:develop/sct-plugins/saocom/docs
    - ssh sardashboard@intranet.aresys.it "cd develop/sct-plugins/saocom/docs && rm latest && ln -s ${PACKAGE_VERSION} latest"
