stages:
  - analysis
  - test
  - build
  - deploy

workflow:
  rules:
    - when: always

variables:
  GIT_DEPTH: 1

.tags_win10_conda:
  tags: ["eo", "win10", "conda"]

.tags_manylinux_2_28_std:
  tags: ["manylinux_2_28"]

.tags_manylinux_2_28:
  tags: ["eotools_manylinux228"]

.tags_win10_new:
  tags: ["eotools_win10"]

.tags_deploy:
  tags: ["eo", "deploy"]

default:
  before_script:
    - cd $SUBPROJECT
