stages:
  - build
  - deploy

workflow:
  rules:
    - when: always

variables:
  GIT_DEPTH: 1

.tags_manylinux_2_28_std:
  tags: ["manylinux_2_28"]

# === build ==================================================================
# ============================================================================
build_docs:
  stage: build
  extends:
    - .tags_manylinux_2_28_std
  script:
    - python3.12 -m pip install nox
    - python3.12 -m nox -f ./nox_common.py -s build_doc
  artifacts:
    expire_in: 2 weeks
    paths:
      - ./documentation*.zip
